plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/user/SmartThingsPublic/sabbatical-site"
publishOrigin = "config"
base = "/home/user/SmartThingsPublic/sabbatical-site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]